[project]
name = "learning-litestar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litestar[standard,sqlalchemy,jwt]>=2.18.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.12.0",
]
